import {
  DashboardOutlined,
  ShoppingCartOutlined,
  UserOutlined,
  PictureOutlined,
  GiftOutlined,
  UsergroupAddOutlined,
  MailOutlined,
  ShoppingOutlined,
  SettingOutlined,
  MobileOutlined,
  FileTextOutlined,
  EditOutlined,
} from "@ant-design/icons"
import { APP_PREFIX_PATH } from "configs/AppConfig"

const mainNavTree = [
  {
    key: "main",
    path: `${APP_PREFIX_PATH}/main`,
    title: "Основные",
    icon: "",
    breadcrumb: false,
    submenu: [
      {
        key: "main-dashboard",
        path: `${APP_PREFIX_PATH}/main/dashboard`,
        title: "Дешборд",
        icon: DashboardOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "main-planner",
        path: `${APP_PREFIX_PATH}/main/planner`,
        title: "Планировщик",
        icon: EditOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "main-catalog",
        path: `${APP_PREFIX_PATH}/main/catalog`,
        title: "Каталог",
        icon: ShoppingCartOutlined,
        breadcrumb: false,
        submenu: [
          {
            key: "main-catalog-goods",
            path: `${APP_PREFIX_PATH}/main/catalog/goods`,
            title: "Товары",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "main-catalog-categories",
            path: `${APP_PREFIX_PATH}/main/catalog/categories`,
            title: "Категории",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "main-catalog-collections",
            path: `${APP_PREFIX_PATH}/main/catalog/collections`,
            title: "Коллекции",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "main-catalog-combos",
            path: `${APP_PREFIX_PATH}/main/catalog/combos`,
            title: "Комбо",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
        ],
      },
      {
        key: "main-orders",
        path: `${APP_PREFIX_PATH}/main/orders`,
        title: "Заказы",
        icon: ShoppingOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "main-clients",
        path: `${APP_PREFIX_PATH}/main/clients`,
        title: "Клиенты",
        icon: UserOutlined,
        breadcrumb: false,
        submenu: [
          {
            key: "main-clientsList",
            path: `${APP_PREFIX_PATH}/main/clients/clients-list`,
            title: "Список клиентов",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "main-clients-clientsGroups",
            path: `${APP_PREFIX_PATH}/main/clients/clients-groups`,
            title: "Группы клиентов",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
        ],
      },
      {
        key: "main-banners",
        path: `${APP_PREFIX_PATH}/main/banners`,
        title: "Баннеры",
        icon: PictureOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "main-promocodes",
        path: `${APP_PREFIX_PATH}/main/promocodes`,
        title: "Промокоды",
        icon: GiftOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "main-offlinePlaces",
        path: `${APP_PREFIX_PATH}/main/offlinePlaces`,
        title: "Оффлайн точки",
        icon: GiftOutlined,
        breadcrumb: false,
        submenu: [
          {
            key: "main-offlinePlaces-addresses",
            path: `${APP_PREFIX_PATH}/main/offlinePlaces/addresses`,
            title: "Адреса",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "main-offlinePlaces-geofences",
            path: `${APP_PREFIX_PATH}/main/offlinePlaces/geofences`,
            title: "Геозоны",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
        ],
      },
      {
        key: "main-employees",
        path: `${APP_PREFIX_PATH}/main/employees`,
        title: "Сотрудники",
        icon: UsergroupAddOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "main-mailings",
        path: `${APP_PREFIX_PATH}/main/mailings`,
        title: "Рассылки",
        icon: MailOutlined,
        breadcrumb: false,
        submenu: [],
      },
    ],
  },
]

const systemNavTree = [
  {
    key: "system",
    path: `${APP_PREFIX_PATH}/system`,
    title: "Системные",
    icon: "",
    breadcrumb: false,
    submenu: [
      {
        key: "system-settings",
        path: `${APP_PREFIX_PATH}/system/settings`,
        title: "Настройки",
        icon: SettingOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "system-mobile-app",
        path: `${APP_PREFIX_PATH}/system/mobile-app`,
        title: "Мобильное приложение",
        icon: MobileOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "system-logs",
        path: `${APP_PREFIX_PATH}/system/logs`,
        title: "Логи",
        icon: FileTextOutlined,
        breadcrumb: false,
        submenu: [],
      },
    ],
  },
]

const navigationConfig = [...mainNavTree, ...systemNavTree]

export default navigationConfig
